In [52]:
# import module for web_scraping
from splinter import Browser
from bs4 import BeautifulSoup
import time
from datetime import datetime

In [53]:
# launch Google Chrome
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

In [54]:
# initial URL 
url = "https://www.oilandgasjobsearch.com/jobs"
baseurl = "https://www.oilandgasjobsearch.com"

In [55]:
# Access initial URL

browser.visit(url)
time.sleep(10)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

# Prepare empty list 
job_url_list = []

In [56]:
# get hyperlink address to each job detail
job_url_per_page = soup.find_all('a', class_='data-results-content')
for eachjob in job_url_per_page:
    job_url_list.append(baseurl + eachjob["href"])

job_url_list

['https://www.oilandgasjobsearch.com/job/J3R54K76JJPC3HGF6CP?ipath=CRJR1',
 'https://www.oilandgasjobsearch.com/job/J3M2HT780M7T8LT5LZL?ipath=CRJR2',
 'https://www.oilandgasjobsearch.com/job/J3T1F96JGV1WS58QSLQ?ipath=CRJR3',
 'https://www.oilandgasjobsearch.com/job/J3S0H16M7K64F466369?ipath=CRJR4',
 'https://www.oilandgasjobsearch.com/job/J3W5JY60RYKNWH1K594?ipath=CRJR5',
 'https://www.oilandgasjobsearch.com/job/J3R2BB6GBCK405SS7RW?ipath=CRJR6',
 'https://www.oilandgasjobsearch.com/job/J3P87B719R7M6HL7S5S?ipath=CRJR7',
 'https://www.oilandgasjobsearch.com/job/J3W6626JMD116JV85TJ?ipath=CRJR8',
 'https://www.oilandgasjobsearch.com/job/J3M0756CY9Z4J467TKZ?ipath=CRJR9',
 'https://www.oilandgasjobsearch.com/job/J3M1CX6NVLPTH48D34K?ipath=CRJR10',
 'https://www.oilandgasjobsearch.com/job/J3N0215X2CFY3CQ850S?ipath=CRJR11',
 'https://www.oilandgasjobsearch.com/job/J3S7RS6WL79F4Z6QMZY?ipath=CRJR12',
 'https://www.oilandgasjobsearch.com/job/J3S58C681F1DH2Q4JHR?ipath=CRJR13',
 'https://www.oilandgasjobsearch.com/job/J3W21Z71GQ7M52C155R?ipath=CRJR14',
 'https://www.oilandgasjobsearch.com/job/J3N51Z6H151ZDH6F7YP?ipath=CRJR15',
 'https://www.oilandgasjobsearch.com/job/J3T4Y76QJ15KTXPPMCY?ipath=CRJR16',
 'https://www.oilandgasjobsearch.com/job/J3V1W36LGTSMY7GBSNL?ipath=CRJR17',
 'https://www.oilandgasjobsearch.com/job/J3W1D568H8RB3NY4DN5?ipath=CRJR18',
 'https://www.oilandgasjobsearch.com/job/J3Q3YK5X4X8PDMF4ZVL?ipath=CRJR19',
 'https://www.oilandgasjobsearch.com/job/J3W31F6VLV8YDZQY37K?ipath=CRJR20']

In [57]:
# click next load button
nextload = soup.find_all('a', class_="btn btn-clear btn-clear-blue b-i")

In [58]:
# Do getting URLs while nextload button appears in the display
while len(nextload) > 0 :
    nextpage = baseurl + nextload[0]["href"]
    browser.visit(nextpage)
    time.sleep(10)

    html = browser.html
    soup = BeautifulSoup(html, 'html.parser')
    job_url_per_page = soup.find_all('a', class_='data-results-content')
    for eachjob in job_url_per_page:
        job_url_list.append(baseurl + eachjob["href"])

    nextload = soup.find_all('a', class_="btn btn-clear btn-clear-blue b-i")

In [59]:
len(job_url_list)

4959

In [60]:
import pandas as pd

In [61]:
# save the data in pandas dataframe 
df = pd.DataFrame(job_url_list,columns=['job_url'])

In [62]:
# save the data to csv file
df.to_csv('job_url.csv')

In [63]:
# prepare empty dictionary for job details
page_detail = {"title":[],"employer":[],"location":[],"worktype":[],"skill":[]}

In [64]:
# launch Google Chrome
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)
# to show the progress
i = 1

In [ ]:
# get position, employer, location, worktype and skii requirments and store them into dictionary 
for eachpage in job_url_list:


    browser.visit(eachpage)
    time.sleep(2)

    html = browser.html
    soup = BeautifulSoup(html, 'html.parser')
    try:
        title = soup.find(class_="data-display-header_info-content").find("h2").get_text()
    except:
        title = ""
    
    try:
        employer = soup.find(class_="data-details").find_all("span")[0].get_text()
    except:
        employer = ""

    try:
        location = soup.find(class_="data-details").find_all("span")[1].get_text()
    except:
        location = ""
    
    try:
        worktype = soup.find(class_="data-details").find_all("span")[2].get_text()
    except:
        worktype = ""

    skill_list = []
    try:
        for each in soup.find_all(class_="check-bubble"):
            skill_list.append(each.get_text())
    except:
        skill_list- []
 
    page_detail["title"].append(title)
    page_detail["employer"].append(employer)
    page_detail["location"].append(location)
    page_detail["worktype"].append(worktype)
    page_detail["skill"].append(skill_list) 
    
    print(f"{i}/4867 is done")
    i = i + 1

In [66]:
# convert dict to Dataframe 
df_detail = pd.DataFrame(page_detail)

In [67]:
# Save dataframe to csv
df_detail.to_csv('job_detail.csv')

In [125]:
#Clean up Dataframe using Pandas
clean_df_detail = df_detail[(df_detail["title"]!="") & (df_detail["location"]!="")]
clean_df_detail["url"] = df["job_url"]

C:\Users\khiro\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [127]:
# Dependencies
import requests
import json

# Google developer API key
from config import g_key

# Target city

In [140]:
# Use geo coding to get lat/lng, State information
def geocoding(location):
    target_url = f'https://maps.googleapis.com/maps/api/geocode/json?address={location}&key={g_key}'
    geo_data = requests.get(target_url).json()
    try:
        formatted_address = geo_data["results"][0]["formatted_address"]
        country = formatted_address.split(", ")[-1]
        latlng = geo_data["results"][0]["geometry"]["location"]
    except:
        formatted_address =""
        country =""
        latlng = ""
        
    return formatted_address, country, latlng

# To extract information from geocoding function return data
def address(data):
    return data[0]

def country(data):
    return data[1]

def latlng(data):
    return data[2]

In [141]:
geocoding("KWT-Al Ahmadi")

('Ahmadi, Kuwait', 'Kuwait', {'lat': 29.083461, 'lng': 48.07347619999999})

In [142]:
clean_df_detail["geocoding"] = clean_df_detail["location"].map(geocoding)

C:\Users\khiro\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [143]:
clean_df_detail.head()

,title,employer,location,worktype,skill,url,geocoding
0,Material Controller,OILANDGAS,"Southaven, Mississippi",Full-Time,"[Warehousing, Forklift Truck, Housekeeping]",https://www.oilandgasjobsearch.com/job/J3R54K7...,"(Southaven, MS, USA, USA, {'lat': 34.9918587, ..."
1,Lead Contracts Engineer,OILANDGAS,KWT-Al Ahmadi,Full-Time,"[Management, Engineering, Risk Management, Pro...",https://www.oilandgasjobsearch.com/job/J3M2HT7...,"(Ahmadi, Kuwait, Kuwait, {'lat': 29.083461, 'l..."
2,Contract Engineer,OILANDGAS,KWT-Al Ahmadi,Full-Time,"[Management, Engineering, Risk Management, Pro...",https://www.oilandgasjobsearch.com/job/J3T1F96...,"(Ahmadi, Kuwait, Kuwait, {'lat': 29.083461, 'l..."
3,Lead Projects Controls Engineer,OILANDGAS,KWT-Al Ahmadi,Full-Time,"[Scheduling, Finance, Accounting, Auditing, Fo...",https://www.oilandgasjobsearch.com/job/J3S0H16...,"(Ahmadi, Kuwait, Kuwait, {'lat': 29.083461, 'l..."
4,Hydrogeologist,OILANDGAS,AUS-WA-Perth,Full-Time,"[Groundwater, Hydrogeology, Geology, Water Res...",https://www.oilandgasjobsearch.com/job/J3W5JY6...,"(Perth WA, Australia, Australia, {'lat': -31.9..."

In [144]:
clean_df_detail["formatted_address"] = clean_df_detail["geocoding"].map(address)
clean_df_detail["country"] = clean_df_detail["geocoding"].map(country)
clean_df_detail["latlng"] = clean_df_detail["geocoding"].map(latlng)

C:\Users\khiro\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\khiro\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\khiro\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [145]:
new_df = clean_df_detail[["title","worktype","skill","url","formatted_address","country","latlng"]]

In [148]:
final_df = new_df[new_df["formatted_address"]!=""]

,title,worktype,skill,url,formatted_address,country,latlng
0,Material Controller,Full-Time,"[Warehousing, Forklift Truck, Housekeeping]",https://www.oilandgasjobsearch.com/job/J3R54K7...,"Southaven, MS, USA",USA,"{'lat': 34.9918587, 'lng': -90.0022958}"
1,Lead Contracts Engineer,Full-Time,"[Management, Engineering, Risk Management, Pro...",https://www.oilandgasjobsearch.com/job/J3M2HT7...,"Ahmadi, Kuwait",Kuwait,"{'lat': 29.083461, 'lng': 48.07347619999999}"
2,Contract Engineer,Full-Time,"[Management, Engineering, Risk Management, Pro...",https://www.oilandgasjobsearch.com/job/J3T1F96...,"Ahmadi, Kuwait",Kuwait,"{'lat': 29.083461, 'lng': 48.07347619999999}"
3,Lead Projects Controls Engineer,Full-Time,"[Scheduling, Finance, Accounting, Auditing, Fo...",https://www.oilandgasjobsearch.com/job/J3S0H16...,"Ahmadi, Kuwait",Kuwait,"{'lat': 29.083461, 'lng': 48.07347619999999}"
4,Hydrogeologist,Full-Time,"[Groundwater, Hydrogeology, Geology, Water Res...",https://www.oilandgasjobsearch.com/job/J3W5JY6...,"Perth WA, Australia",Australia,"{'lat': -31.9505269, 'lng': 115.8604572}"
...,...,...,...,...,...,...,...
4954,AR Accountant,Full-Time,"[Accounting, Positive Attitude, Reconciliation...",https://www.oilandgasjobsearch.com/job/J3V8H66...,"Cluj-Napoca, Romania",Romania,"{'lat': 46.7712101, 'lng': 23.6236353}"
4955,Application Support I,Full-Time,"[Distributors, Self Motivation, Leadership, Cu...",https://www.oilandgasjobsearch.com/job/J3W6VS6...,"936 N Blount St, Raleigh, NC 27604, USA",USA,"{'lat': 35.7933595, 'lng': -78.63535759999999}"
4956,Replenishment Analyst,Full-Time,"[Manufacturing, Manufacturing Operations, Kanb...",https://www.oilandgasjobsearch.com/job/J3Q6L66...,"Elyria, OH 44035, USA",USA,"{'lat': 41.3683798, 'lng': -82.10764859999999}"
4957,Sales Administrator,Full-Time,"[Creativity, Business Administration, Accounti...",https://www.oilandgasjobsearch.com/job/J3R0KJ7...,"Cluj-Napoca, Romania",Romania,"{'lat': 46.7712101, 'lng': 23.6236353}"
4958,Senior Compensation Analyst,Full-Time,"[Management, Customer Interaction Management, ...",https://www.oilandgasjobsearch.com/job/J3Q4MQ6...,"Sidney, OH 45365, USA",USA,"{'lat': 40.2842164, 'lng': -84.1554987}"

In [150]:
# adjust country name 
replace_dic = {"Singapore 126978":"Singapore",
"Taiwan 600":"Taiwan",
"Abu Dhabi - United Arab Emirates":"UAE",
"Jeddah Saudi Arabia":"Saudi Arabia",
"Dubai - United Arab Emirates":"UAE",
"Singapore 127371":"Singapore",
"Taiwan 505":"Taiwan",
"Singapore 569623":"Singapore",
"Sharjah - United Arab Emirates":"USE",
"Al Khobar Saudi Arabia":"Saudi Arabia",
"Singapore 159346":"Singapore",
"Turaif Saudi Arabia":"Saudi Arabia",
"Al Manama - United Arab Emirates":"UAE",
"Taif Saudi Arabia":"Saudi Arabia",
"Fujairah - United Arab Emirates":"UAE",
"Yanbu Saudi Arabia":"Saudi Arabia"}

In [151]:
# replace using replace_dic
final_df["country"] = final_df["country"].replace(replace_dic)

C:\Users\khiro\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [152]:
final_df

,title,worktype,skill,url,formatted_address,country,latlng
0,Material Controller,Full-Time,"[Warehousing, Forklift Truck, Housekeeping]",https://www.oilandgasjobsearch.com/job/J3R54K7...,"Southaven, MS, USA",USA,"{'lat': 34.9918587, 'lng': -90.0022958}"
1,Lead Contracts Engineer,Full-Time,"[Management, Engineering, Risk Management, Pro...",https://www.oilandgasjobsearch.com/job/J3M2HT7...,"Ahmadi, Kuwait",Kuwait,"{'lat': 29.083461, 'lng': 48.07347619999999}"
2,Contract Engineer,Full-Time,"[Management, Engineering, Risk Management, Pro...",https://www.oilandgasjobsearch.com/job/J3T1F96...,"Ahmadi, Kuwait",Kuwait,"{'lat': 29.083461, 'lng': 48.07347619999999}"
3,Lead Projects Controls Engineer,Full-Time,"[Scheduling, Finance, Accounting, Auditing, Fo...",https://www.oilandgasjobsearch.com/job/J3S0H16...,"Ahmadi, Kuwait",Kuwait,"{'lat': 29.083461, 'lng': 48.07347619999999}"
4,Hydrogeologist,Full-Time,"[Groundwater, Hydrogeology, Geology, Water Res...",https://www.oilandgasjobsearch.com/job/J3W5JY6...,"Perth WA, Australia",Australia,"{'lat': -31.9505269, 'lng': 115.8604572}"
...,...,...,...,...,...,...,...
4954,AR Accountant,Full-Time,"[Accounting, Positive Attitude, Reconciliation...",https://www.oilandgasjobsearch.com/job/J3V8H66...,"Cluj-Napoca, Romania",Romania,"{'lat': 46.7712101, 'lng': 23.6236353}"
4955,Application Support I,Full-Time,"[Distributors, Self Motivation, Leadership, Cu...",https://www.oilandgasjobsearch.com/job/J3W6VS6...,"936 N Blount St, Raleigh, NC 27604, USA",USA,"{'lat': 35.7933595, 'lng': -78.63535759999999}"
4956,Replenishment Analyst,Full-Time,"[Manufacturing, Manufacturing Operations, Kanb...",https://www.oilandgasjobsearch.com/job/J3Q6L66...,"Elyria, OH 44035, USA",USA,"{'lat': 41.3683798, 'lng': -82.10764859999999}"
4957,Sales Administrator,Full-Time,"[Creativity, Business Administration, Accounti...",https://www.oilandgasjobsearch.com/job/J3R0KJ7...,"Cluj-Napoca, Romania",Romania,"{'lat': 46.7712101, 'lng': 23.6236353}"
4958,Senior Compensation Analyst,Full-Time,"[Management, Customer Interaction Management, ...",https://www.oilandgasjobsearch.com/job/J3Q4MQ6...,"Sidney, OH 45365, USA",USA,"{'lat': 40.2842164, 'lng': -84.1554987}"

In [154]:
final_df.to_csv("dataset.csv")